### PR TITLE
chore: update creevey

### PR DESCRIPTION
**Pull request by wKich**
Hello. Glad to see, you install creevey for your project. Let me help you with initial setup.

I prefer use next version (0.7) of creevey, because it contains significant improvements and bug fixes, soon I will release stable version.

I init minimal creevey config and add some screenshots to your project. But I can't add `.gitattributes` to fully init Git LFS setup. So I recommend to add that file with `*.png filter=lfs diff=lfs merge=lfs -text` content and also install git-lfs into your machine. Git LFS prevents from store binary data in git commit history.

Feel free to ask me about creevey or if you have any issues with it.

### CODE REVIEW

**Comment by Carduelis** [comment]
@wKich Thank you very much for you contribution. To be honest I wasn't be able to run it properly first time.
I admire your help, will definitely try it out!

**Comment by wKich** [comment]
Yeah. I know, 0.6 version not work properly with new storybook features, like mdx, args, new preview.js format, sorry for that. I hope, you'll enjoy creevey. If you have questions or issues, feel free to ask me.

**Review by Carduelis — APPROVED** [review]

**Comment by Carduelis** [comment]
@wKich Hi! Thank you for your help, again)

I merged, tried to run everything, has some questions:
1. Why did you delete a line with `npm run selenium`? What was the motivation?
2. When I run the script, I got this warning, (probably, it's because, I'm on Windows). Do you know where to look up to fix the joined path (note, there `C:\jamstack\gorazdo` path is doubled)
image
Which gave me a lot of such errors:
image
3. Btw, do you have a guide/an example of how to set Creevey up as a part of GitLab pipelines?

**Comment by wKich** [comment]
1. It's because creevey starts selenoid under the hood, so you don't need to start it manually. You also can define custom docker images for browsers if you would like.
2. I think this warning is ok. At least, storybook load configuration. I could figure out why it output warning

**Comment by wKich** [comment]
3. Can you share your gitlab config?

**Comment by wKich** [comment]
I didn't see that path is doubled.

image

But anyway, as you can see, in two lines after the warning, storybook outputed `info => Adding stories defined in "/home/ki/Projects/creevey/.storybook/main.js".`

**Comment by wKich** [comment]
I tried to setup creevey in gitlab ci. The main problem is gitlab provide only docker executor. So there is few options, how to use creevey.

- Use image with locally installed browsers, or install them on before script. I will add support local browsers for creevey, but I don't recommend to use it because environment on CI and on your local machine could be different
- Use docker-in-docker, but creevey don't support this option yet
- Use external executor, such as vps with installed gitlab-runner
- Use github actions

I recommend last option

**Comment by wKich** [comment]
Tried one more time
image


Does the error from 3-rd point raise only on CI?

**Pull request merged**
